webtalk_init -webtalk_dir E:/VHDL/VivadoProjects/DDVHD_Lab3B_v2/DDVHD_Lab3B_v2.sim/sim_1/behav/xsim/xsim.dir/Fibonacci_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 18 19:43:58 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174238993_1777531742_210673935_605" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fad5c1f1-1bdc-4b43-ad29-7b92f5b11669" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dcb76ea64f2a4557b5f5a162257479b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6672_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2279388015 -regid "174238993_1777531742_210673935_605" -xml E:/VHDL/VivadoProjects/DDVHD_Lab3B_v2/DDVHD_Lab3B_v2.sim/sim_1/behav/xsim/xsim.dir/Fibonacci_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/VHDL/VivadoProjects/DDVHD_Lab3B_v2/DDVHD_Lab3B_v2.sim/sim_1/behav/xsim/xsim.dir/Fibonacci_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/VHDL/VivadoProjects/DDVHD_Lab3B_v2/DDVHD_Lab3B_v2.sim/sim_1/behav/xsim/xsim.dir/Fibonacci_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
