webtalk_init -webtalk_dir E:/VHDL/VivadoProjects/DDVHD_Lab3B_v2/DDVHD_Lab3B_v2.sim/sim_1/behav/xsim/xsim.dir/Fibonacci_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 21 16:36:21 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174238993_177724661_210696558_703" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "76c6157e-b1f3-416d-a07c-ae9bd4bda940" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dcb76ea64f2a4557b5f5a162257479b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "64" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6836_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1033696107 -regid "174238993_177724661_210696558_703" -xml E:/VHDL/VivadoProjects/DDVHD_Lab3B_v2/DDVHD_Lab3B_v2.sim/sim_1/behav/xsim/xsim.dir/Fibonacci_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/VHDL/VivadoProjects/DDVHD_Lab3B_v2/DDVHD_Lab3B_v2.sim/sim_1/behav/xsim/xsim.dir/Fibonacci_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/VHDL/VivadoProjects/DDVHD_Lab3B_v2/DDVHD_Lab3B_v2.sim/sim_1/behav/xsim/xsim.dir/Fibonacci_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
